### ISSUE TITLE
[BUG] Brief description

### ISSUE THREAD

**Issue by Mistahmilla** [KoenZomers/RingRecordingDownload#13]
**Describe the bug**
I am getting an error message. I tried both the current version (windows x64) and several prior versions. In the current version it is saying "Authentication of the session failed".

**Screenshots**
C:\Users\directory\RingDownloader>RingRecordingDownload -username <username> -password <password> -list -ignorecachedtoken

Ring Recordings Download Tool v2.1.0.0 by Koen Zomers

Connecting to Ring services
Authenticating using provided username and password
Unhandled exception. KoenZomers.Ring.Api.Exceptions.AuthenticationFailedException: Authentication of the session failed
   at KoenZomers.Ring.Api.HttpUtility.FormPost(Uri url, Dictionary`2 formFields, NameValueCollection headerFields)
   at KoenZomers.Ring.Api.Session.Authenticate(String operatingSystem, String hardwareId, String appBrand, String deviceModel, String deviceName, String resolution, String appVersion, Nullable`1 appInstallationDate, String manufacturer, String deviceType, String architecture, String language, String twoFactorAuthCode)
   at KoenZomers.Ring.RecordingDownload.Program.Main(String[] args)
   at KoenZomers.Ring.RecordingDownload.Program.<Main>(String[] args)

**Comment by vincentr** [comment]
Having the same issue. It appeared to stop working on 6/2/2023.

**Comment by ronwarner** [comment]
To point out what is probably obvious, this is likely the same thing causing issues 24 and 25 in the API Repo.

**Comment by KoenZomers** [comment]
Check https://github.com/KoenZomers/RingApi/issues/24
