### ISSUE TITLE
Unhandled JsonExeption during login

### ISSUE THREAD

**Issue by donl** [KoenZomers/RingRecordingDownload#21]
This is what I am experiencing when trying to use the tool currently.  It was working well previously.  I updated to the latest version and it is still giving the same error.

```
Ring Recordings Download Tool v3.1.0.0 by Koen Zomers

Connecting to Ring services
Authenticating using provided username and password
Unhandled exception. System.Text.Json.JsonException: '<' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at KoenZomers.Ring.Api.Session.Authenticate(String operatingSystem, String hardwareId, String appBrand, String deviceModel, String deviceName, String resolution, String appVersion, Nullable`1 appInstallationDate, String manufacturer, String deviceType, String architecture, String language, String twoFactorAuthCode)
   at KoenZomers.Ring.RecordingDownload.Program.Main(String[] args)
   at KoenZomers.Ring.RecordingDownload.Program.<Main>(String[] args)
Aborted (core dumped)
```

**Comment by jorgegarciaavila** [comment]
Same issue, just noticed but it start happening on 03/07/2024

**Comment by danespinosa** [comment]
Hi there, I have a PR ready with the fixes, I hope I can create the binaries soon, what platforms are you using to run the application?
@jorgegarciaavila  @donl 

https://github.com/KoenZomers/RingRecordingDownload/pull/22

**Comment by jorgegarciaavila** [comment]
@danespinosa debian 12, thanks

**Comment by danespinosa** [comment]
New version has been published! 
https://github.com/KoenZomers/RingRecordingDownload/releases/tag/3.1.0.0
